version: '3.8'

services:
  postgresdb:
    image: postgres:16.2-alpine
    restart: always 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data/
  web:
    build: .
    volumes:
      - .:/code
    command: python /code/manage.py runserver 0.0.0.0:8080
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=postgres
    ports:
      - 8080:8080
    depends_on:
      - postgresdb

volumes: 
  postgres_db: